# Generates font6x12.bend: Spleen 6x12 (BSD-2, design/fonts/) as three U32
# match functions. Each glyph is 12 rows x 6 bits; rows 4k..4k+3 pack into
# word k, row r at bits (r%4)*6 .. +5, bit 0 = leftmost pixel.
#
# Why matches, not a List: font8x8 walked a 1024-cell List per glyph row
# (O(index) per lookup, and the list was rebuilt per string). Bend 2.0.20+
# compiles dense U32 matches cheaply, so a match is O(1) with no allocation.
#
# Codes 1-7 carry symbols Spleen's ASCII range lacks (drawn here by hand):
#   1 ● dot   2 … ellipsis   3 ▸ pointer   4 ✓ check   5 ↑   6 ↓   7 ◆
# Run: python3 tools_gen_font_spleen.py > font6x12.bend
import sys

BDF = "design/fonts/spleen-6x12.bdf"
EXTRA = {
    1: ["......", "......", "......", "......", ".###..", "#####.", "#####.", "#####.", ".###..", "......", "......", "......"],
    2: ["......", "......", "......", "......", "......", "......", "......", "......", "#.#.#.", "......", "......", "......"],
    3: ["......", "......", "......", "#.....", "##....", "###...", "####..", "###...", "##....", "#.....", "......", "......"],
    4: ["......", "......", "......", "......", ".....#", "....#.", "#..#..", ".##...", ".#....", "......", "......", "......"],
    5: ["......", "..#...", ".###..", "#.#.#.", "..#...", "..#...", "..#...", "..#...", "..#...", "......", "......", "......"],
    6: ["......", "..#...", "..#...", "..#...", "..#...", "..#...", "#.#.#.", ".###..", "..#...", "......", "......", "......"],
    7: ["......", "......", "..#...", ".###..", "#####.", ".###..", "..#...", "......", "......", "......", "......", "......"],
}


def parse_bdf(path):
    glyphs, cur, rows = {}, None, None
    for line in open(path, encoding="latin-1"):
        t = line.split()
        if not t:
            continue
        if t[0] == "ENCODING":
            cur = int(t[1])
        elif t[0] == "BBX":
            assert t[1:] == ["6", "12", "0", "-3"], t
        elif t[0] == "BITMAP":
            rows = []
        elif t[0] == "ENDCHAR":
            if cur is not None and 32 <= cur <= 126:
                # BDF bytes are MSB-first (bit 7 = leftmost); flip to LSB-first.
                glyphs[cur] = [sum(1 << x for x in range(6) if (r >> (7 - x)) & 1) for r in rows]
            cur, rows = None, None
        elif rows is not None:
            rows.append(int(t[0], 16))
    return glyphs


glyphs = parse_bdf(BDF)
for code, art in EXTRA.items():
    glyphs[code] = [sum(1 << x for x, ch in enumerate(row) if ch == "#") for row in art]
assert all(len(v) == 12 for v in glyphs.values())


def word(rows, k):
    return sum(rows[k * 4 + i] << (i * 6) for i in range(4))


out = [
    "import Base",
    "",
    "# font6x12.bend: Spleen 6x12 by Frederic Cambus (BSD-2-Clause, see",
    "# design/fonts/LICENSE-spleen), plus hand-drawn symbols at codes 1-7.",
    "# Generated by tools_gen_font_spleen.py; do not hand-edit.",
    "# glyph_w(code, k): rows 4k..4k+3 of a glyph, 6 bits each, row r at bits",
    "# (r%4)*6.., bit 0 = leftmost pixel. Unknown codes draw blank.",
    "",
]
for k in range(3):
    out.append(f"def glyph_w{k}(+code: U32) -> U32:")
    out.append("  match code:")
    for code in sorted(glyphs):
        w = word(glyphs[code], k)
        if w:
            out.append(f"    case {code}: {w}")
    out.append("    case _: 0")
    out.append("")
out += [
    "def glyph_w(+code: U32, +k: U32) -> U32:",
    "  match k:",
    "    case 0: glyph_w0(code)",
    "    case 1: glyph_w1(code)",
    "    case _: glyph_w2(code)",
    "",
]
sys.stdout.write("\n".join(out))
