# Generates font.bend: the 1024-byte font8x8_basic table as a pure List<U32>
# instead of match arms.
#
# Rationale (2026-09-20): Bend 2.0.18's native C codegen uses ~9MB RAM per
# U32 match arm (measured: 1x256-arm = 2.3GB peak; 4x256-arm = SIGKILL at
# 4.8GB). Splitting into smaller matches does NOT help — cost is linear in
# TOTAL arms. So the table is plain data: 16 chunk functions of 64 Con cells.
# Zero match arms for the data; lookup is a list walk (font_nth, same shape
# as the already-compiling list_get in term.bend).
#
# font_byte(tbl, idx): idx = code*8 + row (0..1023) -> bitmap byte.
# Bit 0 = leftmost pixel of the row (LSB-first, the font8x8 convention).
# Callers build the table once via font_data() and thread it through.
# Byte-identical to the old match-based font (verified in Python).
import re

src = open("/home/hatch/workspace/apps/shell-os/pure/font_bak_match.bend").read()
table = {}
for m in re.finditer(r"def fq([0-3])\(lo: U32\) -> U32:\n  match lo:\n((?:    case \d+: \d+\n)+)", src):
    q = int(m.group(1))
    for line in m.group(2).split("\n"):
        mm = re.match(r"    case (\d+): (\d+)", line)
        if mm:
            table[q * 256 + int(mm.group(1))] = int(mm.group(2))
assert len(table) == 1024, len(table)

out = []
out.append("import Base")
out.append("")
out.append("# font.bend — font8x8_basic by Daniel Hepper, public domain.")
out.append("# Generated by tools_gen_font_list.py — do not hand-edit.")
out.append("# font_byte(tbl, idx): idx = code*8 + row (0..1023) -> bitmap byte (U32).")
out.append("# Bit 0 = leftmost pixel of the row (LSB-first, the font8x8 convention).")
out.append("#")
out.append("# The 1024 bytes live in a List<U32> (16 chunks of 64 cells). A previous")
out.append("# version used 4x256-arm U32 matches; Bend 2.0.18's native C codegen needs")
out.append("# ~9MB RAM per match arm (measured 2026-09-20: 1x256 arms = 2.3GB peak,")
out.append("# 4x256 arms = SIGKILL at 4.8GB), so match-based tables cannot go native.")
out.append("# font_data() builds the table once; callers thread it through.")
out.append("")

for c in range(16):
    out.append(f"def font_c{c}(tail: List<&2, U32>) -> List<&2, U32>:")
    expr = "tail"
    for i in range(63, -1, -1):
        expr = f"Con{{{table[c * 64 + i]}, {expr}}}"
    out.append(f"  {expr}")
    out.append("")

out.append("def font_data() -> List<&2, U32>:")
nested = "Nil{}"
for c in range(15, -1, -1):
    nested = f"font_c{c}({nested})"
out.append(f"  {nested}")
out.append("")
out.append("# Index walk (same shape as list_get in term.bend).")
out.append("def font_nth(+xs: List<&2, U32>, +idx: U32) -> U32:")
out.append("  match xs, idx:")
out.append("    case Nil{}, _: 0")
out.append("    case h <> _, 0: h")
out.append("    case _ <> t, i: font_nth(t, U32.sub(i, 1))")
out.append("")
out.append("def font_byte(+tbl: List<&2, U32>, +idx: U32) -> U32:")
out.append("  font_nth(tbl, idx)")

with open("/home/hatch/workspace/apps/shell-os/pure/font.bend", "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote font.bend,", len(out), "lines")
