# Generates font8x16.bend: Spleen 8x16 (BSD-2, design/fonts/) as four U32
# match functions. Each glyph is 16 rows x 8 bits; rows 4k..4k+3 pack into
# word k, row r at bits (r%4)*8 .. +7, bit 0 = leftmost pixel.
#
# Why matches, not a List: the old font8x8 walked a 1024-cell List per glyph
# row (O(index) per lookup, rebuilt per string). Bend 2.0.20+ compiles dense
# U32 matches cheaply, so a match is O(1) with no allocation.
#
# Codes 1-7 carry symbols outside ASCII: 1 ● dot, 2 … ellipsis, 3 ▸ pointer,
# 4 ✓ check, 5 ↑, 6 ↓, 7 ◆. Spleen draws all but ▸ and ✓, which are drawn
# here by hand on the same 8x16 grid (baseline under row 11).
# Run: python3 tools_gen_font_spleen.py > font8x16.bend
import sys

BDF = "design/fonts/spleen-8x16.bdf"
FROM_BDF = {1: 0x25CF, 2: 0x2026, 5: 0x2191, 6: 0x2193, 7: 0x25C6}
BLANK = "........"
HAND = {
    3: [BLANK] * 5 + [".#......", ".##.....", ".###....", ".####...", ".###....", ".##.....", ".#......"] + [BLANK] * 4,
    4: [BLANK] * 6 + [".......#", "......#.", ".....#..", "#...#...", ".#.#....", "..#....."] + [BLANK] * 4,
}


def parse_bdf(path):
    glyphs, cur, rows = {}, None, None
    for line in open(path, encoding="latin-1"):
        t = line.split()
        if not t:
            continue
        if t[0] == "ENCODING":
            cur = int(t[1])
        elif t[0] == "BBX":
            assert t[1:] == ["8", "16", "0", "-4"], t
        elif t[0] == "BITMAP":
            rows = []
        elif t[0] == "ENDCHAR":
            if cur is not None:
                # BDF bytes are MSB-first (bit 7 = leftmost); flip to LSB-first.
                glyphs[cur] = [sum(1 << x for x in range(8) if (r >> (7 - x)) & 1) for r in rows]
            cur, rows = None, None
        elif rows is not None:
            rows.append(int(t[0], 16))
    return glyphs


src = parse_bdf(BDF)
glyphs = {c: src[c] for c in range(32, 127)}
for code, uni in FROM_BDF.items():
    glyphs[code] = src[uni]
for code, art in HAND.items():
    glyphs[code] = [sum(1 << x for x, ch in enumerate(row) if ch == "#") for row in art]
assert all(len(v) == 16 for v in glyphs.values())


def word(rows, k):
    return sum(rows[k * 4 + i] << (i * 8) for i in range(4))


out = [
    "import Base",
    "",
    "# font8x16.bend: Spleen 8x16 by Frederic Cambus (BSD-2-Clause, see",
    "# design/fonts/LICENSE-spleen); symbols at codes 1-7 (see the generator).",
    "# Generated by tools_gen_font_spleen.py; do not hand-edit.",
    "# glyph_wK(code): rows 4K..4K+3 of a glyph, 8 bits each, row r at bits",
    "# (r%4)*8.., bit 0 = leftmost pixel. Unknown codes draw blank.",
    "",
]
for k in range(4):
    out.append(f"def glyph_w{k}(+code: U32) -> U32:")
    out.append("  match code:")
    for code in sorted(glyphs):
        w = word(glyphs[code], k)
        if w:
            out.append(f"    case {code}: {w}")
    out.append("    case _: 0")
    out.append("")
sys.stdout.write("\n".join(out))
