# Generates font_nested.bend: the same 1024-byte font8x8_basic table as font.bend
# but with a three-level dispatch where no match has more than 16 arms.
#
# Rationale (2026-09-20): Bend 2.0.18's NATIVE C codegen SIGKILLs (exit -9,
# ~4.8GB peak RSS) on font.bend's 256-arm U32 matches — even a single 256-arm
# function alone. (The old claim "256-arm matches compile natively without
# issue" was verified only via check/interpreter/JS, never native codegen.)
# The JS backend handles the wide matches fine; only the C backend blows up.
#
# Layout: idx = code*8 + row (0..1023)
#   hi  = idx >> 8          (0..3)
#   mid = (idx >> 4) & 15   (0..15)
#   lo  = idx & 15          (0..15)
#   font_byte(idx) = fb2(hi, mid, lo)
#     fb2: 4-arm match on hi  -> fb2_{h}(mid, lo)
#     fb2_{h}: 16-arm match on mid -> fb_{h}_{m}(lo)
#     fb_{h}_{m}: 16-arm match on lo -> byte
# Byte-for-byte identical to font.bend's font_byte (verified by the probe).
import re

src = open("/home/hatch/workspace/apps/shell-os/pure/font.bend").read()
table = {}
for m in re.finditer(r"def fq([0-3])\(lo: U32\) -> U32:\n  match lo:\n((?:    case \d+: \d+\n)+)", src):
    q = int(m.group(1))
    for line in m.group(2).split("\n"):
        mm = re.match(r"    case (\d+): (\d+)", line)
        if mm:
            table[q * 256 + int(mm.group(1))] = int(mm.group(2))
assert len(table) == 1024, len(table)
assert all(table[i] == table.get(i) for i in range(1024))

out = []
out.append("import Base")
out.append("")
out.append("# font_nested.bend — font8x8_basic by Daniel Hepper, public domain.")
out.append("# Generated by tools_gen_font_nested.py — do not hand-edit.")
out.append("# font_byte(idx): idx = code*8 + row (0..1023) -> bitmap byte (U32 0..255).")
out.append("# Bit 0 = leftmost pixel of the row (LSB-first, the font8x8 convention).")
out.append("#")
out.append("# Three-level dispatch (4/16/16 arms): Bend 2.0.18's native C codegen")
out.append("# SIGKILLs on 256-arm U32 matches (~4.8GB peak, verified 2026-09-20),")
out.append("# so no single match exceeds 16 arms. Byte-identical to font.bend.")
out.append("")

# Leaf level: 64 functions x 16 arms.
for h in range(4):
    for m in range(16):
        out.append(f"def fb_{h}_{m}(lo: U32) -> U32:")
        out.append("  match lo:")
        for lo in range(16):
            out.append(f"    case {lo}: {table[h * 256 + m * 16 + lo]}")
        out.append("    case _: 0")
        out.append("")

# Mid level: 4 functions x 16 arms.
for h in range(4):
    out.append(f"def fb2_{h}(mid: U32, lo: U32) -> U32:")
    out.append("  match mid:")
    for m in range(16):
        out.append(f"    case {m}: fb_{h}_{m}(lo)")
    out.append(f"    case _: fb_{h}_0(lo)")
    out.append("")

# Top level: 4 arms.
out.append("def fb2(hi: U32, mid: U32, lo: U32) -> U32:")
out.append("  match hi:")
for h in range(4):
    out.append(f"    case {h}: fb2_{h}(mid, lo)")
out.append("    case _: fb2_0(mid, lo)")
out.append("")

out.append("def font_byte(+idx: U32) -> U32:")
out.append("  fb2(U32.shrn(idx, 8n), U32.and(U32.shrn(idx, 4n), 15), U32.and(idx, 15))")

with open("/home/hatch/workspace/apps/shell-os/pure/font_nested.bend", "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote font_nested.bend,", len(out), "lines")
