# Reads the FONT table from /tmp/gen_font.py and emits a two-level
# font.bend: font_byte -> font_q (4 arms) -> fq0..fq3 (256 arms each).
# Rationale (2026-09-20): a single 1024-arm match on U32 OOMs Bend 2.0.18's
# native C codegen (SIGKILL, exit 137); 256-arm matches compile fine.
import re
src = open("/tmp/gen_font.py").read()
FONT = eval(src[src.index("FONT = [")+7:src.index("assert len(FONT)")])
assert len(FONT) == 128
table = []
for code, g in enumerate(FONT):
    assert len(g) == 16, (code, g)
    for row in range(8):
        table.append(int(g[row*2:row*2+2], 16))
assert len(table) == 1024
out = []
out.append("import Base")
out.append("")
out.append("# font.bend — font8x8_basic by Daniel Hepper, public domain.")
out.append("# Generated by /tmp/gen_font2.py — do not hand-edit.")
out.append("# font_byte(idx): idx = code*8 + row (0..1023) -> bitmap byte (U32 0..255).")
out.append("# Bit 0 = leftmost pixel of the row (LSB-first, the font8x8 convention).")
out.append("#")
out.append("# Two-level dispatch (4 x 256 arms): a single 1024-arm U32 match")
out.append("# OOMs Bend 2.0.18's native codegen (exit 137, verified 2026-09-20);")
out.append("# 256-arm matches compile natively without issue.")
out.append("")
for q in range(4):
    out.append(f"def fq{q}(lo: U32) -> U32:")
    out.append("  match lo:")
    for i in range(256):
        out.append(f"    case {i}: {table[q*256+i]}")
    out.append("    case _: 0")
    out.append("")
out.append("def font_q(hi: U32, lo: U32) -> U32:")
out.append("  match hi:")
out.append("    case 0: fq0(lo)")
out.append("    case 1: fq1(lo)")
out.append("    case 2: fq2(lo)")
out.append("    case _: fq3(lo)")
out.append("")
out.append("def font_byte(idx: U32) -> U32:")
out.append("  font_q(U32.shrn(idx, 8n), U32.and(idx, 255))")
with open("/home/hatch/workspace/apps/shell-os/pure/font.bend", "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote font.bend,", len(out), "lines")
